import { 
  Sparkles, 
  ShieldAlert, 
  User, 
  Bot, 
  Radio,
  Heart
} from 'lucide-react';

export const PRESETS = [
  {
    id: 'normal',
    name: 'Normal Voice',
    subtitle: 'Natural / Clean',
    icon: User,
    badge: '1:1 Original',
    color: '#10b981',
    glow: 'rgba(16, 185, 129, 0.25)',
    description: 'Bypasses all pitch filters for pure microphone clarity.',
  },
  {
    id: 'girl',
    name: 'Girl Voice',
    subtitle: 'Feminine Pitch & Formants',
    icon: Heart,
    badge: '+7 st · Formant',
    color: '#ec4899',
    glow: 'rgba(236, 72, 153, 0.25)',
    description: 'Natural female voice: higher pitch plus a shorter vocal tract, with breathy air.',
  },
  {
    id: 'kid',
    name: 'Kid Voice',
    subtitle: 'High Pitch + Formants',
    icon: Sparkles,
    badge: '+9 st · Formant',
    color: '#f59e0b',
    glow: 'rgba(245, 158, 11, 0.25)',
    description: 'Elevates pitch with high-frequency acoustic vocal tract resonance.',
  },
  {
    id: 'deep',
    name: 'Deep Voice (Big Man)',
    subtitle: 'Low Pitch + Sub-Bass',
    icon: ShieldAlert,
    badge: '-5 st · Formant',
    color: '#6366f1',
    glow: 'rgba(99, 102, 241, 0.25)',
    description: 'Thick baritone chest frequency boost with pitch downshift.',
  },
  {
    id: 'robot',
    name: 'Cyber Robot',
    subtitle: 'Metallic Modulation',
    icon: Bot,
    badge: 'Ring Mod',
    color: '#06b6d4',
    glow: 'rgba(6, 182, 212, 0.25)',
    description: 'Robotic carrier wave modulation and synthetic timbre.',
  },
  {
    id: 'radio',
    name: 'Walkie-Talkie',
    subtitle: 'Telecom Bandpass',
    icon: Radio,
    badge: '300-3400 Hz',
    color: '#f97316',
    glow: 'rgba(249, 115, 22, 0.25)',
    description: 'Vintage telephone bandpass filter with warm analog distortion.',
  },
];
